// <auto-generated />
using System;
using LinkerBoard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkerBoard.API.Migrations
{
    [DbContext(typeof(LinkerBoardDbContext))]
    [Migration("20240530124643_UserConfigWithBogusData")]
    partial class UserConfigWithBogusData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkerBoard.API.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fceeb08-5998-4db3-965e-5cb2d93243dd"),
                            CreatedAt = new DateOnly(2024, 5, 30),
                            Email = "Justin.Konopelski64@yahoo.com",
                            UpdatedAt = new DateOnly(2024, 4, 15),
                            Username = "Justin_Konopelski43"
                        },
                        new
                        {
                            Id = new Guid("5894960c-ac2f-4b80-a731-d921f946f7c6"),
                            CreatedAt = new DateOnly(2024, 5, 4),
                            Email = "Tara.Cummerata@hotmail.com",
                            Username = "Tara.Cummerata30"
                        },
                        new
                        {
                            Id = new Guid("0ff3beea-a032-4096-b2bb-45a4b4599164"),
                            CreatedAt = new DateOnly(2023, 12, 25),
                            Email = "Rickey94@gmail.com",
                            Username = "Rickey56"
                        },
                        new
                        {
                            Id = new Guid("2a1f1726-5cf9-45a1-b84b-d629c2ddabb8"),
                            CreatedAt = new DateOnly(2023, 12, 11),
                            Email = "Tabitha.Maggio47@gmail.com",
                            Username = "Tabitha.Maggio"
                        },
                        new
                        {
                            Id = new Guid("1f127154-e12a-4348-a1fb-75010c12e005"),
                            CreatedAt = new DateOnly(2024, 2, 18),
                            Email = "Mario95@hotmail.com",
                            Username = "Mario.Gislason"
                        },
                        new
                        {
                            Id = new Guid("0ccf903d-526f-4ac5-8d08-a3af1f3b2286"),
                            CreatedAt = new DateOnly(2024, 3, 21),
                            Email = "Violet_Windler@yahoo.com",
                            Username = "Violet_Windler80"
                        },
                        new
                        {
                            Id = new Guid("94aef0f5-40fc-492e-9b3c-f13ae07580a4"),
                            CreatedAt = new DateOnly(2024, 3, 26),
                            Email = "Wilfred95@hotmail.com",
                            Username = "Wilfred36"
                        },
                        new
                        {
                            Id = new Guid("abf3cd16-e6f0-42e3-981e-6cc46734204e"),
                            CreatedAt = new DateOnly(2024, 4, 4),
                            Email = "Louise.Hessel@yahoo.com",
                            Username = "Louise81"
                        },
                        new
                        {
                            Id = new Guid("b26c7361-54bf-4f24-8cb8-0ecc04aebd4c"),
                            CreatedAt = new DateOnly(2024, 5, 14),
                            Email = "Claude_Beer9@yahoo.com",
                            Username = "Claude.Beer"
                        },
                        new
                        {
                            Id = new Guid("adc4253a-2ee3-4245-b71e-0c067c5339a3"),
                            CreatedAt = new DateOnly(2023, 9, 5),
                            Email = "Della.Rosenbaum@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 12, 13),
                            Username = "Della_Rosenbaum29"
                        },
                        new
                        {
                            Id = new Guid("f1575608-59fd-496d-ae38-02d3c9f11f60"),
                            CreatedAt = new DateOnly(2024, 2, 14),
                            Email = "Kevin.Koch32@hotmail.com",
                            UpdatedAt = new DateOnly(2023, 11, 8),
                            Username = "Kevin.Koch17"
                        },
                        new
                        {
                            Id = new Guid("0fe34001-27e2-43b7-a57f-458a84c7052b"),
                            CreatedAt = new DateOnly(2023, 7, 27),
                            Email = "Beatrice46@gmail.com",
                            UpdatedAt = new DateOnly(2024, 1, 5),
                            Username = "Beatrice62"
                        },
                        new
                        {
                            Id = new Guid("2bc6d2a5-60b9-4038-bfe7-0f86bc24c564"),
                            CreatedAt = new DateOnly(2023, 9, 10),
                            Email = "Harriet_Steuber58@hotmail.com",
                            Username = "Harriet7"
                        },
                        new
                        {
                            Id = new Guid("fce822b7-835b-4821-9089-27045a631134"),
                            CreatedAt = new DateOnly(2023, 6, 18),
                            Email = "Rolando46@hotmail.com",
                            Username = "Rolando_Lueilwitz"
                        },
                        new
                        {
                            Id = new Guid("08ac8593-e31d-439f-b041-2eb7dc3a3831"),
                            CreatedAt = new DateOnly(2024, 1, 31),
                            Email = "Tiffany_Funk80@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 6, 28),
                            Username = "Tiffany_Funk66"
                        },
                        new
                        {
                            Id = new Guid("a815a7af-d534-429c-93b4-af8f4550e6b8"),
                            CreatedAt = new DateOnly(2023, 11, 19),
                            Email = "Dwight_Wilderman@gmail.com",
                            UpdatedAt = new DateOnly(2023, 11, 30),
                            Username = "Dwight.Wilderman54"
                        },
                        new
                        {
                            Id = new Guid("48549b33-2e06-40d1-bead-1dda91629a45"),
                            CreatedAt = new DateOnly(2024, 3, 26),
                            Email = "Kendra_OConner@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 10, 31),
                            Username = "Kendra88"
                        },
                        new
                        {
                            Id = new Guid("a9e6bf08-8736-45f5-bfad-ca6a497b2724"),
                            CreatedAt = new DateOnly(2024, 5, 25),
                            Email = "Roger.Heller20@gmail.com",
                            UpdatedAt = new DateOnly(2023, 12, 24),
                            Username = "Roger.Heller"
                        },
                        new
                        {
                            Id = new Guid("8fbc91bb-59f3-4efb-a1ef-bb6f0dd0f758"),
                            CreatedAt = new DateOnly(2024, 4, 21),
                            Email = "Sue_Beatty@gmail.com",
                            Username = "Sue_Beatty"
                        },
                        new
                        {
                            Id = new Guid("b6807d32-c4f1-4027-be0a-cb6fd54487c3"),
                            CreatedAt = new DateOnly(2023, 9, 3),
                            Email = "Grant.Rogahn@hotmail.com",
                            Username = "Grant.Rogahn3"
                        },
                        new
                        {
                            Id = new Guid("025e350b-6614-488b-9205-65420c58e9fe"),
                            CreatedAt = new DateOnly(2024, 5, 2),
                            Email = "Shawna97@hotmail.com",
                            Username = "Shawna68"
                        },
                        new
                        {
                            Id = new Guid("39fc981c-001d-4d27-8a9e-e9ef99d665af"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Email = "Ricky.Considine69@hotmail.com",
                            Username = "Ricky13"
                        },
                        new
                        {
                            Id = new Guid("2f9559b0-ffd9-440b-8f9e-44a5c78767f5"),
                            CreatedAt = new DateOnly(2023, 9, 6),
                            Email = "Felicia98@yahoo.com",
                            Username = "Felicia_Sporer"
                        },
                        new
                        {
                            Id = new Guid("126ab011-58d7-4898-b97d-f67fc9655f29"),
                            CreatedAt = new DateOnly(2024, 5, 6),
                            Email = "Orville_Little@yahoo.com",
                            Username = "Orville.Little53"
                        },
                        new
                        {
                            Id = new Guid("b67224f7-5965-4f46-b721-dd29893444dc"),
                            CreatedAt = new DateOnly(2023, 7, 7),
                            Email = "Jane.Flatley49@gmail.com",
                            UpdatedAt = new DateOnly(2024, 1, 18),
                            Username = "Jane.Flatley40"
                        },
                        new
                        {
                            Id = new Guid("ec266827-cfb2-4745-af0b-ed84102f387f"),
                            CreatedAt = new DateOnly(2023, 8, 1),
                            Email = "Arnold.Weissnat@gmail.com",
                            Username = "Arnold94"
                        },
                        new
                        {
                            Id = new Guid("ba52045d-c9ab-4f36-a0aa-59020c6f3e51"),
                            CreatedAt = new DateOnly(2024, 5, 21),
                            Email = "Karla98@gmail.com",
                            Username = "Karla39"
                        },
                        new
                        {
                            Id = new Guid("3a60c57c-0727-48fe-9dd2-6fa791daa129"),
                            CreatedAt = new DateOnly(2023, 8, 14),
                            Email = "Kenneth.Hayes@gmail.com",
                            Username = "Kenneth_Hayes"
                        },
                        new
                        {
                            Id = new Guid("d72fb72a-798b-4909-bc09-32e4984b9960"),
                            CreatedAt = new DateOnly(2023, 7, 16),
                            Email = "Joann_Batz96@hotmail.com",
                            Username = "Joann.Batz90"
                        },
                        new
                        {
                            Id = new Guid("bda17694-00ed-4369-b5ed-4f650b86dd63"),
                            CreatedAt = new DateOnly(2023, 6, 25),
                            Email = "Wendell_Rippin@yahoo.com",
                            Username = "Wendell_Rippin77"
                        },
                        new
                        {
                            Id = new Guid("36882642-facc-4512-9466-2cb2baa471ee"),
                            CreatedAt = new DateOnly(2024, 3, 5),
                            Email = "Alexis_Kertzmann81@yahoo.com",
                            Username = "Alexis20"
                        },
                        new
                        {
                            Id = new Guid("da9e7c9d-ea26-4463-9662-1e8a0e075150"),
                            CreatedAt = new DateOnly(2024, 4, 2),
                            Email = "Luis49@yahoo.com",
                            Username = "Luis_Collins"
                        },
                        new
                        {
                            Id = new Guid("1b886b5d-3919-4b9d-b1ad-c19b719d0619"),
                            CreatedAt = new DateOnly(2024, 1, 28),
                            Email = "Vickie_Skiles6@yahoo.com",
                            Username = "Vickie.Skiles"
                        },
                        new
                        {
                            Id = new Guid("19f7690f-956c-4a21-84a5-33cadc882c95"),
                            CreatedAt = new DateOnly(2023, 7, 28),
                            Email = "Kim.Lesch@gmail.com",
                            Username = "Kim_Lesch27"
                        },
                        new
                        {
                            Id = new Guid("f1201475-9c4d-4929-aaba-383f5963825a"),
                            CreatedAt = new DateOnly(2024, 3, 28),
                            Email = "Harold.Feest@gmail.com",
                            Username = "Harold0"
                        },
                        new
                        {
                            Id = new Guid("ffc97380-6172-4d8e-99c6-aabb65c05247"),
                            CreatedAt = new DateOnly(2023, 10, 8),
                            Email = "Jeanette50@gmail.com",
                            UpdatedAt = new DateOnly(2023, 6, 25),
                            Username = "Jeanette45"
                        },
                        new
                        {
                            Id = new Guid("47e333fe-851b-4a7c-80d2-a40560e1c089"),
                            CreatedAt = new DateOnly(2023, 8, 25),
                            Email = "Neal.Murray@hotmail.com",
                            Username = "Neal_Murray"
                        },
                        new
                        {
                            Id = new Guid("ed87c45f-5ea9-4d9c-b7ea-ade5e4966743"),
                            CreatedAt = new DateOnly(2024, 2, 10),
                            Email = "Faith_Harber@hotmail.com",
                            UpdatedAt = new DateOnly(2023, 11, 16),
                            Username = "Faith.Harber76"
                        },
                        new
                        {
                            Id = new Guid("cc40775b-8fb3-44ee-8a87-347decca2a9d"),
                            CreatedAt = new DateOnly(2024, 2, 6),
                            Email = "Frederick80@yahoo.com",
                            Username = "Frederick_Barrows64"
                        },
                        new
                        {
                            Id = new Guid("ee32b695-4a35-4322-bcdd-10a9d53a67da"),
                            CreatedAt = new DateOnly(2024, 3, 8),
                            Email = "Billie_Rempel92@yahoo.com",
                            Username = "Billie26"
                        },
                        new
                        {
                            Id = new Guid("40407a21-91d2-4409-b5a5-dc35def12d18"),
                            CreatedAt = new DateOnly(2024, 5, 12),
                            Email = "Dallas1@yahoo.com",
                            Username = "Dallas71"
                        },
                        new
                        {
                            Id = new Guid("9daba698-7874-4147-9e2e-312900d977f4"),
                            CreatedAt = new DateOnly(2024, 1, 15),
                            Email = "Kathy_Cassin17@gmail.com",
                            Username = "Kathy.Cassin"
                        },
                        new
                        {
                            Id = new Guid("7a93c18c-cf3e-4136-a55f-64ce7f2d3a8e"),
                            CreatedAt = new DateOnly(2023, 8, 8),
                            Email = "Elmer29@gmail.com",
                            Username = "Elmer_Senger13"
                        },
                        new
                        {
                            Id = new Guid("1caffa2d-4916-496e-8c40-05cabbe9038a"),
                            CreatedAt = new DateOnly(2023, 7, 12),
                            Email = "Jeannette.Ledner@yahoo.com",
                            Username = "Jeannette.Ledner1"
                        },
                        new
                        {
                            Id = new Guid("03b19c17-f8ee-4591-b064-aa56720276ce"),
                            CreatedAt = new DateOnly(2023, 9, 2),
                            Email = "Christopher1@hotmail.com",
                            Username = "Christopher52"
                        },
                        new
                        {
                            Id = new Guid("914c4603-545d-4654-abcc-dbb27cb45237"),
                            CreatedAt = new DateOnly(2023, 7, 30),
                            Email = "Veronica_Waelchi@hotmail.com",
                            Username = "Veronica_Waelchi"
                        },
                        new
                        {
                            Id = new Guid("a09f4281-801b-4b80-9cc1-ae3486ba564d"),
                            CreatedAt = new DateOnly(2023, 6, 30),
                            Email = "Alejandro.Mraz79@yahoo.com",
                            UpdatedAt = new DateOnly(2024, 5, 17),
                            Username = "Alejandro.Mraz"
                        },
                        new
                        {
                            Id = new Guid("6e4b1d4b-1576-4e19-b0f3-279521d7e5f4"),
                            CreatedAt = new DateOnly(2024, 5, 25),
                            Email = "Gwen_Hammes@yahoo.com",
                            Username = "Gwen_Hammes50"
                        },
                        new
                        {
                            Id = new Guid("138fabdf-bdd1-43da-9a49-06b1571400d7"),
                            CreatedAt = new DateOnly(2023, 6, 23),
                            Email = "Earl.Auer3@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 6, 10),
                            Username = "Earl32"
                        },
                        new
                        {
                            Id = new Guid("31c43f58-8658-46d6-96c6-eb947c19f62b"),
                            CreatedAt = new DateOnly(2023, 7, 30),
                            Email = "Courtney52@gmail.com",
                            Username = "Courtney78"
                        },
                        new
                        {
                            Id = new Guid("2c0949d4-588c-4cba-a805-4337e452199a"),
                            CreatedAt = new DateOnly(2023, 11, 18),
                            Email = "Lowell.Johns28@gmail.com",
                            Username = "Lowell.Johns"
                        },
                        new
                        {
                            Id = new Guid("1de70ad1-5334-4477-995e-4ba05d41d5c6"),
                            CreatedAt = new DateOnly(2024, 4, 30),
                            Email = "Martha52@gmail.com",
                            UpdatedAt = new DateOnly(2024, 4, 9),
                            Username = "Martha_Buckridge"
                        },
                        new
                        {
                            Id = new Guid("9396c32a-983b-46c7-84b6-e03bdcf3ce54"),
                            CreatedAt = new DateOnly(2024, 5, 22),
                            Email = "Vernon53@yahoo.com",
                            Username = "Vernon.Schultz87"
                        },
                        new
                        {
                            Id = new Guid("9bc1d626-e029-416a-8acd-cdc216537b4f"),
                            CreatedAt = new DateOnly(2023, 6, 24),
                            Email = "Amelia53@hotmail.com",
                            Username = "Amelia58"
                        },
                        new
                        {
                            Id = new Guid("92a3c552-95cd-4ec1-8146-6430a2ab77c4"),
                            CreatedAt = new DateOnly(2023, 10, 26),
                            Email = "Tommie.Effertz@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 6, 22),
                            Username = "Tommie3"
                        },
                        new
                        {
                            Id = new Guid("23046167-d381-4a91-b234-2bd729ca4b0a"),
                            CreatedAt = new DateOnly(2023, 6, 22),
                            Email = "Ethel_Veum90@yahoo.com",
                            Username = "Ethel.Veum"
                        },
                        new
                        {
                            Id = new Guid("284ad785-3d42-49dc-8f13-6dd42ed7d6ab"),
                            CreatedAt = new DateOnly(2024, 3, 25),
                            Email = "Kay2@yahoo.com",
                            Username = "Kay_Monahan37"
                        },
                        new
                        {
                            Id = new Guid("502b2700-62bd-4c0d-86ce-b9220bb4458c"),
                            CreatedAt = new DateOnly(2023, 7, 16),
                            Email = "Gustavo.Hagenes@hotmail.com",
                            UpdatedAt = new DateOnly(2023, 6, 21),
                            Username = "Gustavo.Hagenes24"
                        },
                        new
                        {
                            Id = new Guid("2f3b7caa-6b3f-483f-b34b-de0426078377"),
                            CreatedAt = new DateOnly(2023, 7, 4),
                            Email = "Rose.Adams@gmail.com",
                            Username = "Rose84"
                        },
                        new
                        {
                            Id = new Guid("e4dd0a82-b632-48e9-a340-9bcc6682fdcb"),
                            CreatedAt = new DateOnly(2023, 10, 19),
                            Email = "Ben_Quigley40@hotmail.com",
                            Username = "Ben.Quigley"
                        },
                        new
                        {
                            Id = new Guid("8092c62d-66d8-4579-8709-883f5cb17218"),
                            CreatedAt = new DateOnly(2023, 11, 24),
                            Email = "Lola4@hotmail.com",
                            Username = "Lola_Jaskolski"
                        },
                        new
                        {
                            Id = new Guid("d8936dca-e398-4ac1-a3d0-88238600cce4"),
                            CreatedAt = new DateOnly(2024, 1, 17),
                            Email = "William_Braun@hotmail.com",
                            Username = "William.Braun74"
                        },
                        new
                        {
                            Id = new Guid("1865ffa7-8e81-49ba-838c-0c19e5cbd67c"),
                            CreatedAt = new DateOnly(2023, 10, 27),
                            Email = "Alicia4@yahoo.com",
                            UpdatedAt = new DateOnly(2023, 7, 5),
                            Username = "Alicia64"
                        },
                        new
                        {
                            Id = new Guid("eeb1921d-506e-4e2c-9202-63b8746890ca"),
                            CreatedAt = new DateOnly(2023, 9, 26),
                            Email = "Freddie_Labadie@yahoo.com",
                            Username = "Freddie10"
                        },
                        new
                        {
                            Id = new Guid("62fe3904-115e-4e5d-989a-4a8bab253600"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Email = "Cecelia5@yahoo.com",
                            Username = "Cecelia_Douglas"
                        },
                        new
                        {
                            Id = new Guid("c974232e-0f82-4b29-8337-df16a4a45b45"),
                            CreatedAt = new DateOnly(2023, 6, 9),
                            Email = "Shawn_Turcotte@gmail.com",
                            UpdatedAt = new DateOnly(2023, 12, 20),
                            Username = "Shawn.Turcotte"
                        },
                        new
                        {
                            Id = new Guid("4dd00251-297c-4470-aaf2-0c1cf7534261"),
                            CreatedAt = new DateOnly(2024, 3, 31),
                            Email = "Minnie26@hotmail.com",
                            UpdatedAt = new DateOnly(2023, 12, 25),
                            Username = "Minnie.Miller11"
                        },
                        new
                        {
                            Id = new Guid("b14e5271-e8ff-40ab-903a-0b927f9dacc1"),
                            CreatedAt = new DateOnly(2023, 12, 18),
                            Email = "Rodolfo_Gusikowski@hotmail.com",
                            Username = "Rodolfo90"
                        },
                        new
                        {
                            Id = new Guid("941483d7-33da-4cb3-a49c-37f0651df455"),
                            CreatedAt = new DateOnly(2023, 11, 12),
                            Email = "Amy.Zulauf51@hotmail.com",
                            Username = "Amy35"
                        },
                        new
                        {
                            Id = new Guid("2dbbbc52-f532-44a9-bc4b-6f36542c2a65"),
                            CreatedAt = new DateOnly(2024, 1, 10),
                            Email = "Dan56@hotmail.com",
                            Username = "Dan_Predovic"
                        },
                        new
                        {
                            Id = new Guid("0af7ba5c-1ba9-4847-ac09-75c8d5858ba3"),
                            CreatedAt = new DateOnly(2023, 11, 29),
                            Email = "Eunice76@hotmail.com",
                            Username = "Eunice.Hyatt60"
                        },
                        new
                        {
                            Id = new Guid("3809b76f-f539-4228-a98c-be99e27cf52b"),
                            CreatedAt = new DateOnly(2023, 7, 16),
                            Email = "Moses_Boyer@gmail.com",
                            Username = "Moses_Boyer47"
                        },
                        new
                        {
                            Id = new Guid("d7147495-f771-4c05-b167-fe0d436c54e7"),
                            CreatedAt = new DateOnly(2023, 10, 7),
                            Email = "Sherry.Schimmel@yahoo.com",
                            Username = "Sherry16"
                        },
                        new
                        {
                            Id = new Guid("10a6a906-305e-4c18-8c37-7a71f4197e2d"),
                            CreatedAt = new DateOnly(2023, 6, 19),
                            Email = "Bob56@gmail.com",
                            Username = "Bob_Kunde"
                        },
                        new
                        {
                            Id = new Guid("67093e73-e3b0-409b-8937-46b879c536be"),
                            CreatedAt = new DateOnly(2024, 3, 8),
                            Email = "Elena.Dicki@gmail.com",
                            Username = "Elena.Dicki"
                        },
                        new
                        {
                            Id = new Guid("986cebc7-53ca-45b0-adc0-64e6ec2d72bd"),
                            CreatedAt = new DateOnly(2023, 7, 2),
                            Email = "Keith.Toy@hotmail.com",
                            UpdatedAt = new DateOnly(2023, 6, 18),
                            Username = "Keith_Toy97"
                        },
                        new
                        {
                            Id = new Guid("acc56aed-f164-4324-8d27-44b4f8a22e1a"),
                            CreatedAt = new DateOnly(2023, 6, 18),
                            Email = "Terri50@yahoo.com",
                            Username = "Terri_McLaughlin84"
                        },
                        new
                        {
                            Id = new Guid("696e6497-361d-4cd3-9fb5-50a543cafaf8"),
                            CreatedAt = new DateOnly(2024, 4, 10),
                            Email = "Andres_Green62@hotmail.com",
                            UpdatedAt = new DateOnly(2024, 2, 20),
                            Username = "Andres42"
                        },
                        new
                        {
                            Id = new Guid("dea6836a-665f-4285-bd75-1624393dbc97"),
                            CreatedAt = new DateOnly(2024, 2, 13),
                            Email = "Winifred7@yahoo.com",
                            Username = "Winifred_Yundt"
                        },
                        new
                        {
                            Id = new Guid("2e5c3bf6-7fa4-4681-9ac9-6cf99127d22b"),
                            CreatedAt = new DateOnly(2024, 5, 6),
                            Email = "Jamie_Pfannerstill87@yahoo.com",
                            Username = "Jamie.Pfannerstill"
                        },
                        new
                        {
                            Id = new Guid("cb8e4cd0-7766-4353-a90a-1e0fce2542ca"),
                            CreatedAt = new DateOnly(2023, 9, 15),
                            Email = "Kent99@gmail.com",
                            Username = "Kent_Howe34"
                        },
                        new
                        {
                            Id = new Guid("32b53edc-f09b-4587-86f6-0887a6fedfd0"),
                            CreatedAt = new DateOnly(2023, 7, 24),
                            Email = "Leigh_Bogan@gmail.com",
                            Username = "Leigh22"
                        },
                        new
                        {
                            Id = new Guid("a044777a-8428-4d7e-9c20-7d5b52f08fca"),
                            CreatedAt = new DateOnly(2024, 1, 13),
                            Email = "Ernest8@gmail.com",
                            UpdatedAt = new DateOnly(2023, 6, 8),
                            Username = "Ernest67"
                        },
                        new
                        {
                            Id = new Guid("987c52b6-1ba9-4477-89ea-ab0c33c40533"),
                            CreatedAt = new DateOnly(2024, 3, 23),
                            Email = "Lillie_Kub@hotmail.com",
                            UpdatedAt = new DateOnly(2024, 3, 21),
                            Username = "Lillie.Kub"
                        },
                        new
                        {
                            Id = new Guid("7e21ee39-7541-4463-92f7-bd7de69687fa"),
                            CreatedAt = new DateOnly(2023, 10, 5),
                            Email = "Guillermo49@hotmail.com",
                            Username = "Guillermo_Deckow84"
                        },
                        new
                        {
                            Id = new Guid("fbbcf5e4-0da7-42c2-8531-f0a0c38475c4"),
                            CreatedAt = new DateOnly(2023, 11, 16),
                            Email = "Jessica_Thompson@yahoo.com",
                            Username = "Jessica.Thompson71"
                        },
                        new
                        {
                            Id = new Guid("0e9f77b3-6f98-45ae-8730-938bcd6db1a0"),
                            CreatedAt = new DateOnly(2024, 2, 14),
                            Email = "Dean.McClure74@yahoo.com",
                            Username = "Dean48"
                        },
                        new
                        {
                            Id = new Guid("fee7cf44-81f7-44db-88c7-44cbcedba30b"),
                            CreatedAt = new DateOnly(2024, 3, 22),
                            Email = "Brandi_Gottlieb@yahoo.com",
                            Username = "Brandi_Gottlieb"
                        },
                        new
                        {
                            Id = new Guid("f3ddcd7e-08f2-4599-aae7-c4864039fd0d"),
                            CreatedAt = new DateOnly(2024, 4, 11),
                            Email = "Dexter.Wolff98@yahoo.com",
                            Username = "Dexter.Wolff"
                        },
                        new
                        {
                            Id = new Guid("3fbe0e9a-7cac-49eb-af2f-deb7ab24fa89"),
                            CreatedAt = new DateOnly(2023, 12, 17),
                            Email = "Cindy.Pagac@gmail.com",
                            Username = "Cindy_Pagac20"
                        },
                        new
                        {
                            Id = new Guid("24fbf4bf-2879-4339-a2ed-9ee6a9229ba8"),
                            CreatedAt = new DateOnly(2024, 1, 13),
                            Email = "Jimmie23@hotmail.com",
                            Username = "Jimmie.Hirthe8"
                        },
                        new
                        {
                            Id = new Guid("9dea27de-345c-4616-aaf2-127c11d1928c"),
                            CreatedAt = new DateOnly(2023, 12, 30),
                            Email = "Rachael59@hotmail.com",
                            Username = "Rachael74"
                        },
                        new
                        {
                            Id = new Guid("d681fbb0-e577-4d15-a3f7-a59d3f482293"),
                            CreatedAt = new DateOnly(2024, 4, 8),
                            Email = "Jack.Ryan@hotmail.com",
                            Username = "Jack.Ryan"
                        },
                        new
                        {
                            Id = new Guid("8ec5f5cc-26ef-4178-aade-6c5bc5fdaa35"),
                            CreatedAt = new DateOnly(2024, 1, 5),
                            Email = "Jeanne60@hotmail.com",
                            Username = "Jeanne_Kozey"
                        },
                        new
                        {
                            Id = new Guid("f77fbb08-33d8-411c-b8a3-a22d4830adf9"),
                            CreatedAt = new DateOnly(2024, 3, 20),
                            Email = "Abraham73@yahoo.com",
                            Username = "Abraham.DAmore57"
                        },
                        new
                        {
                            Id = new Guid("859b7abd-b290-4b1a-9dd9-cedd20724af3"),
                            CreatedAt = new DateOnly(2023, 12, 14),
                            Email = "Melba_Strosin85@yahoo.com",
                            Username = "Melba54"
                        },
                        new
                        {
                            Id = new Guid("e7127432-46be-4779-9820-883c9ba8c1e1"),
                            CreatedAt = new DateOnly(2024, 3, 6),
                            Email = "Barry.Marks@gmail.com",
                            Username = "Barry0"
                        },
                        new
                        {
                            Id = new Guid("046e62ca-5be3-4b52-b773-f1adb2296348"),
                            CreatedAt = new DateOnly(2023, 8, 20),
                            Email = "Becky_Glover10@gmail.com",
                            Username = "Becky.Glover"
                        },
                        new
                        {
                            Id = new Guid("f0acbe0d-2dfd-400a-afdd-17370b8c09e2"),
                            CreatedAt = new DateOnly(2023, 10, 28),
                            Email = "Ervin22@gmail.com",
                            Username = "Ervin_Wisoky7"
                        },
                        new
                        {
                            Id = new Guid("b5e7cb2e-a9c6-49ef-8405-4829f7c4fe6b"),
                            CreatedAt = new DateOnly(2024, 4, 17),
                            Email = "Marilyn.Orn@hotmail.com",
                            UpdatedAt = new DateOnly(2024, 5, 6),
                            Username = "Marilyn.Orn94"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
